FROM python:3.9-slim
WORKDIR /app
COPY esb.py .
RUN pip install flask requests
#garantiza que el ESB pueda manejar de manera segura las solicitudes de origen cruzado desde el frontend
RUN pip install flask-cors  
EXPOSE 5000
CMD ["python", "esb.py"]